OrderWebPortal/OrderWebPortal/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OrderWebPortal.DataAccessLayer;
using OrderWebPortal.Models;

namespace OrderWebPortal.Controllers
{
    [CheckSession]
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult CompletedOrder()
        {
            //Order order = new Order();

            //List<CompletedOrderEntity> Data = order.GetCompleteOrder();
            return View();
        }
        public JsonResult CompleteOrder(string StartDate, String EndDate)
        {
            Order order = new Order();

            DateTime _StartDate = DateTime.Parse(StartDate, CultureInfo.InvariantCulture);
            DateTime _EndDate = DateTime.Parse(EndDate, CultureInfo.InvariantCulture);

            List<CompletedOrderEntity> Data = order.GetCompleteOrder(_StartDate.ToString("yyyy-MM-dd"), _EndDate.ToString("yyyy-MM-dd"));
            return Json(Data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult NewOrder()
        {
            Order order = new Order();
            List<OrderEntity> Data = order.GetNewOrder();
            return View(Data);
        }
        //public JsonResult Order(string StartDate, String EndDate)
        //{
        //    Order order = new Order();

        //    DateTime _StartDate = DateTime.Parse(StartDate, CultureInfo.InvariantCulture);
        //    DateTime _EndDate = DateTime.Parse(EndDate, CultureInfo.InvariantCulture);

        //    List<OrderEntity> Data = order.GetNewOrder(_StartDate.ToString("yyyy-MM-dd"), _EndDate.ToString("yyyy-MM-dd"));
        //    return Json(Data, JsonRequestBehavior.AllowGet);
        //}

        public ActionResult Orderapproval(string SoID)
        {
            Order order = new Order();
            List<OrderDetailsEntity> OrderList = new List<OrderDetailsEntity>();
            DataSet DS = order.ApprovalData(SoID);
            if (DS.Tables.Count > 0)
            {
                if (DS.Tables[0].Rows.Count > 0)
                {
                    ViewBag.SoID = Convert.ToString(DS.Tables[0].Rows[0]["Soid"]);
                    ViewBag.socode = Convert.ToString(DS.Tables[0].Rows[0]["socode"]);
                    ViewBag.CustomerName = Convert.ToString(DS.Tables[0].Rows[0]["CustomerName"]);
                    ViewBag.deliverydate = Convert.ToString(DS.Tables[0].Rows[0]["deliverydate"]);
                    ViewBag.address = Convert.ToString(DS.Tables[0].Rows[0]["address"]);
                    ViewBag.city = Convert.ToString(DS.Tables[0].Rows[0]["city"]);
                    ViewBag.state = Convert.ToString(DS.Tables[0].Rows[0]["state"]);
                    ViewBag.referenceno = Convert.ToString(DS.Tables[0].Rows[0]["referenceno"]);
                }
                if (DS.Tables[1].Rows.Count > 0)
                {
                    
                    for (int i = 0; i < DS.Tables[1].Rows.Count; i++)
                    {
                        OrderDetailsEntity Details = new OrderDetailsEntity();

                        Details.itemname = Convert.ToString(DS.Tables[1].Rows[i]["itemname"]);

                        Details.itemcatname = Convert.ToString(DS.Tables[1].Rows[i]["itemcatname"]);
                        Details.unitname = Convert.ToString(DS.Tables[1].Rows[i]["unitname"]);
                        Details.qty = Convert.ToString(DS.Tables[1].Rows[i]["qty"]);
                        Details.netrate = Convert.ToString(DS.Tables[1].Rows[i]["netrate"]);
                        Details.totamt = Convert.ToString(DS.Tables[1].Rows[i]["totamt"]);

                        OrderList.Add(Details);
                    }
                }
            }
            DataTable DT1 = order.GetDelPerRecord();
            ViewBag.DelPerRecord = BindDropDown(DT1);
            return View(OrderList);
        }

        public ActionResult ApproveOrderapproval(string SoID)
        {
            Order order = new Order();
            ApprovedOrderEntity apord = new ApprovedOrderEntity();
            List<OrderDetailsEntity> OrderList = new List<OrderDetailsEntity>();
            DataSet DS = order.ApprovalData(SoID);
            if (DS.Tables.Count > 0)
            {
                if (DS.Tables[0].Rows.Count > 0)
                {
                    ViewBag.SoID = Convert.ToString(DS.Tables[0].Rows[0]["Soid"]);
                    ViewBag.socode = Convert.ToString(DS.Tables[0].Rows[0]["socode"]);
                    ViewBag.CustomerName = Convert.ToString(DS.Tables[0].Rows[0]["CustomerName"]);
                    ViewBag.deliverydate = Convert.ToString(DS.Tables[0].Rows[0]["deliverydate"]);
                    ViewBag.address = Convert.ToString(DS.Tables[0].Rows[0]["address"]);
                    ViewBag.city = Convert.ToString(DS.Tables[0].Rows[0]["city"]);
                    ViewBag.state = Convert.ToString(DS.Tables[0].Rows[0]["state"]);
                    ViewBag.referenceno = Convert.ToString(DS.Tables[0].Rows[0]["referenceno"]);

                    apord.Soid = Convert.ToString(DS.Tables[0].Rows[0]["Soid"]);
                    apord.socode = Convert.ToString(DS.Tables[0].Rows[0]["socode"]);
                    apord.CustomerName = Convert.ToString(DS.Tables[0].Rows[0]["CustomerName"]);
                    apord.deliverydate = Convert.ToString(DS.Tables[0].Rows[0]["deliverydate"]);
                    apord.address = Convert.ToString(DS.Tables[0].Rows[0]["address"]);
                    apord.city = Convert.ToString(DS.Tables[0].Rows[0]["city"]);
                    apord.state = Convert.ToString(DS.Tables[0].Rows[0]["state"]);
                    apord.referenceno = Convert.ToString(DS.Tables[0].Rows[0]["referenceno"]);

                }
                if (DS.Tables[1].Rows.Count > 0)
                {

                    for (int i = 0; i < DS.Tables[1].Rows.Count; i++)
                    {
                        OrderDetailsEntity Details = new OrderDetailsEntity();

                        Details.itemname = Convert.ToString(DS.Tables[1].Rows[i]["itemname"]);

                        Details.itemcatname = Convert.ToString(DS.Tables[1].Rows[i]["itemcatname"]);
                        Details.unitname = Convert.ToString(DS.Tables[1].Rows[i]["unitname"]);
                        Details.qty = Convert.ToString(DS.Tables[1].Rows[i]["qty"]);
                        Details.netrate = Convert.ToString(DS.Tables[1].Rows[i]["netrate"]);
                        Details.totamt = Convert.ToString(DS.Tables[1].Rows[i]["totamt"]);

                        OrderList.Add(Details);
                    }
                    apord.orderDetailsEntity = OrderList;
                    ViewBag.orderDetailsEntity = OrderList;
                }
            }
            DataTable DT1 = order.GetDelPerRecord();
            ViewBag.DelPerRecord = BindDropDown(DT1);
            return View(OrderList);
        }

        public ActionResult ReadyForShipOrderapproval(string SoID)
        {
            Order order = new Order();
            ApprovedOrderEntity apord = new ApprovedOrderEntity();
            List<OrderDetailsEntity> OrderList = new List<OrderDetailsEntity>();
            DataSet DS = order.ApprovalData(SoID);
            if (DS.Tables.Count > 0)
            {
                if (DS.Tables[0].Rows.Count > 0)
                {
                    ViewBag.SoID = Convert.ToString(DS.Tables[0].Rows[0]["Soid"]);
                    ViewBag.socode = Convert.ToString(DS.Tables[0].Rows[0]["socode"]);
                    ViewBag.CustomerName = Convert.ToString(DS.Tables[0].Rows[0]["CustomerName"]);
                    ViewBag.deliverydate = Convert.ToString(DS.Tables[0].Rows[0]["deliverydate"]);
                    ViewBag.address = Convert.ToString(DS.Tables[0].Rows[0]["address"]);
                    ViewBag.city = Convert.ToString(DS.Tables[0].Rows[0]["city"]);
                    ViewBag.state = Convert.ToString(DS.Tables[0].Rows[0]["state"]);
                    ViewBag.referenceno = Convert.ToString(DS.Tables[0].Rows[0]["referenceno"]);

                    apord.Soid = Convert.ToString(DS.Tables[0].Rows[0]["Soid"]);
                    apord.socode = Convert.ToString(DS.Tables[0].Rows[0]["socode"]);
                    apord.CustomerName = Convert.ToString(DS.Tables[0].Rows[0]["CustomerName"]);
                    apord.deliverydate = Convert.ToString(DS.Tables[0].Rows[0]["deliverydate"]);
                    apord.address = Convert.ToString(DS.Tables[0].Rows[0]["address"]);
                    apord.city = Convert.ToString(DS.Tables[0].Rows[0]["city"]);
                    apord.state = Convert.ToString(DS.Tables[0].Rows[0]["state"]);
                    apord.referenceno = Convert.ToString(DS.Tables[0].Rows[0]["referenceno"]);

                }
                if (DS.Tables[1].Rows.Count > 0)
                {

                    for (int i = 0; i < DS.Tables[1].Rows.Count; i++)
                    {
                        OrderDetailsEntity Details = new OrderDetailsEntity();

                        Details.itemname = Convert.ToString(DS.Tables[1].Rows[i]["itemname"]);

                        Details.itemcatname = Convert.ToString(DS.Tables[1].Rows[i]["itemcatname"]);
                        Details.unitname = Convert.ToString(DS.Tables[1].Rows[i]["unitname"]);
                        Details.qty = Convert.ToString(DS.Tables[1].Rows[i]["qty"]);
                        Details.netrate = Convert.ToString(DS.Tables[1].Rows[i]["netrate"]);
                        Details.totamt = Convert.ToString(DS.Tables[1].Rows[i]["totamt"]);

                        OrderList.Add(Details);
                    }
                    apord.orderDetailsEntity = OrderList;
                    ViewBag.orderDetailsEntity = OrderList;
                }
            }
            DataTable DT1 = order.GetDelPerRecord();

OrderWebPortal/OrderWebPortal/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OrderWebPortal.Models;
using OrderWebPortal.DataAccessLayer;
using System.Globalization;

namespace OrderWebPortal.Controllers
{
    [CheckSession]
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult salesSummary()
        {
            //Report report = new Report();

            //List<salesSummaryEntity> Data = report.GetsalesSummary();
            return View();
        }
        public JsonResult sales(string StartDate, String EndDate)
        {
            Report report = new Report();

            DateTime _StartDate = DateTime.Parse(StartDate, CultureInfo.InvariantCulture);
            DateTime _EndDate = DateTime.Parse(EndDate, CultureInfo.InvariantCulture);

            List<salesSummaryEntity> Data = report.GetsalesSummary(_StartDate.ToString("yyyy-MM-dd"), _EndDate.ToString("yyyy-MM-dd"));
            return Json(Data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult OrderSummary()
        {
        //    Report report = new Report();
        //    List<OrderSummaryEntity> Data = report.GetOrderSummary();
            return View();
        }

        public JsonResult Order(string StartDate, String EndDate)
        {
            Report report = new Report();

            DateTime _StartDate = DateTime.Parse(StartDate, CultureInfo.InvariantCulture);
            DateTime _EndDate = DateTime.Parse(EndDate, CultureInfo.InvariantCulture);

            List<OrderSummaryEntity> Data = report.GetOrderSummary(_StartDate.ToString("yyyy-MM-dd"), _EndDate.ToString("yyyy-MM-dd"));
            return Json(Data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeliverySummary()
        {
            //Report report = new Report();

            //List<DeliverySummaryEntity> Data = report.GetDeliverySummary();
            return View();
        }

        public JsonResult Delivery(string StartDate, String EndDate)
        {
            Report report = new Report();

            DateTime _StartDate = DateTime.Parse(StartDate, CultureInfo.InvariantCulture);
            DateTime _EndDate = DateTime.Parse(EndDate, CultureInfo.InvariantCulture);

            List<DeliverySummaryEntity> Data = report.GetDeliverySummary(_StartDate.ToString("yyyy-MM-dd"), _EndDate.ToString("yyyy-MM-dd"));
            return Json(Data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ItemWiseOrder()
        {
            //Report report = new Report();

            //List<DeliverySummaryEntity> Data = report.GetDeliverySummary();
            return View();
        }

        public JsonResult ItemOrder(string StartDate, String EndDate)
        {
            Report report = new Report();

            DateTime _StartDate = DateTime.Parse(StartDate, CultureInfo.InvariantCulture);
            DateTime _EndDate = DateTime.Parse(EndDate, CultureInfo.InvariantCulture);

            List<ItemWiseOrderEntity> Data = report.GetItemWiseOrder(_StartDate.ToString("yyyy-MM-dd"), _EndDate.ToString("yyyy-MM-dd"));
            return Json(Data, JsonRequestBehavior.AllowGet);
        }
    }
}

OrderWebPortal/OrderWebPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Balram Pure Ghee </title>
    @Styles.Render("~/Admin/css")
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>                
            </ul>
         
        </nav>

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="@Url.Action("Index", "Home")" class="brand-link">
                <img src="~/Images/logo.png" alt="AdminLTE Logo" class="brand-image"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Balram Pure Ghee</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    @*<div class="image">
                        <img src="Content/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>*@
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="@Url.Action("NewOrder", "Order")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    New Orders
                                    <span class="right badge badge-danger">New</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("ApprovedOrder", "Order")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Approved Order
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("ReadyForShipOrder", "Order")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Ready For Ship Order
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("CompletedOrder", "Order")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Completed Orders
                                    @*<i class="right fas fa-angle-left"></i>*@
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("UserRegistrationList", "Order")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    User Registration
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    Reports
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                @*<li class="nav-item">
                                    <a href="@Url.Action("salesSummary", "Reports")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Sales Summary</p>
                                    </a>
                                </li>*@
                                <li class="nav-item">
                                    <a href="@Url.Action("OrderSummary", "Reports")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Order Summary</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("DeliverySummary", "Reports")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Delivery Report</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("ItemWiseOrder", "Reports")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Item Wise Order</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("SignOut", "Login")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    SignOut
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2020-2021 <a href="http://puredesigheeofindia.co.in">Balram Pure Ghee</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0.0
            </div>
        </footer>
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    @Scripts.Render("~/Admin/script")
    @RenderSection("scripts", required: false)
</body>
</html>